### ISSUE TITLE
Error > throw new Error('unable to determine member type'); on file.ts

### ISSUE THREAD

**Issue by David-Else** [bafolts/tplant#19]
Hi, I get errors. I am using Node 12 on Linux.

Should this file work? Thanks!:

```
$ npx tplant --input game-object.ts > app.puml
/home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:171
                throw new Error('unable to determine member type');
                ^

Error: unable to determine member type
    at getMemberType (/home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:171:23)
    at getMemberReturnType (/home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:96:26)
    at serializeMember (/home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:84:25)
    at /home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:236:36
    at Map.forEach (<anonymous>)
    at serializeInterface (/home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:235:24)
    at visit (/home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:56:25)
    at visitNodes (/home/david/sites/testuml/node_modules/.registry.npmjs.org/typescript/3.4.5/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/home/david/sites/testuml/node_modules/.registry.npmjs.org/typescript/3.4.5/node_modules/typescript/lib/typescript.js:16742:24)
    at /home/david/sites/testuml/node_modules/.registry.npmjs.org/tplant/2.0.4/node_modules/tplant/dist/generateDocumentation.js:30:34
```
on **game-object.ts**:
```
export type Vector2 = [number, number];

export const vectors = {
  add(a: Vector2, b: Vector2): Vector2 {
    return [a[0] + b[0], a[1] + b[1]];
  },
  multiply(a: Vector2, b: Vector2): Vector2 {
    return [a[0] * b[0], a[1] * b[1]];
  },
  get up(): Vector2 {
    return [0, 1];
  },
  get down(): Vector2 {
    return [0, -1];
  },
  get left(): Vector2 {
    return [-1, 0];
  },
  get right(): Vector2 {
    return [1, 0];
  },
};

/**
 * =============================================================================
 * GameObject (modified https://docs.unity3d.com/Manual/class-Transform.html)
 * =============================================================================
 */
interface GameObjectOptions {
  position: Vector2;
  rotation?: number;
  scale?: Vector2;
}

export abstract class GameObject {
  public position: Vector2;
  public rotation?: number;
  public scale: Vector2;

  public constructor({
    position,
    rotation = 0,
    scale = [1, 1],
  }: GameObjectOptions) {
    this.position = position;
    this.rotation = rotation;
    this.scale = scale;
  }
  public static createCharacters<T>({ ...options }: GameFactoryOptions): T[] {
    let character: Character;
    const characters = [];

    for (let index = 0; index < options.numberOf; index += 1) {
      switch (options.Character) {
        case Hero:
          character = new options.Character({
            position: options.positionFn(),
            widthHeight: [50, 25],
          });
          break;

        case Zombie:
          character = new options.Character({
            position: options.positionFn(),
            widthHeight: [50, 25],
            image: options.image,
            // velocity: [1, 1],
          });
          break;

        case Bullet:
          character = new options.Character({
            position: options.positionFn(),
            widthHeight: [5, 25],
            rotation: [10, 10],
          });
          break;

        default:
          break;
      }
      characters.push(character);
    }

    return characters;
  }
}

/**
 * =============================================================================
 * Character
 * =============================================================================
 */
interface CharacterOptions extends GameObjectOptions {
  alive?: boolean;
  velocity?: Vector2;
  widthHeight: Vector2;
}

abstract class Character extends GameObject {
  public alive: boolean;
  public velocity: Vector2;
  public widthHeight: Vector2;
  public abstract imageType: string; // 'bitmap' | 'rectangle';

  public constructor({
    alive = true,
    velocity = [0, 0],
    widthHeight,
    ...characterOptions
  }: CharacterOptions) {
    super(characterOptions);
    this.alive = alive;
    this.velocity = velocity;
    this.widthHeight = vectors.multiply(widthHeight, this.scale);
  }
}

/**
 * =============================================================================
 * Hero
 * =============================================================================
 */
export class Hero extends Character {
  private color = 'red';
  public imageType = 'rectangle';

  public constructor({ ...characterOptions }: CharacterOptions) {
    super(characterOptions);
  }
}

/**
 * =============================================================================
 * Zombie
 * =============================================================================
 */
interface ZombieOptions extends CharacterOptions {
  image: HTMLImageElement;
}

export class Zombie extends Character {
  private image: HTMLImageElement;
  public imageType = 'bitmap';

  public constructor({ image, ...characterOptions }: ZombieOptions) {
    super(characterOptions);
    this.image = image;
  }
}

/**
 * =============================================================================
 * Bullet
 * =============================================================================
 */
export class Bullet extends Character {
  private color = 'green';
  public imageType = 'rectangle';

  public constructor({ ...characterOptions }: CharacterOptions) {
    super(characterOptions);
  }
}

/**
 * =============================================================================
 * Game simple factory pattern
 * =============================================================================
 */

export interface Newable<T> {
  new (...args: any[]): T;
}

interface GameFactoryOptions {
  Character: Newable<Character>; // https://stackoverflow.com/questions/41017287/cannot-use-new-with-expression-typescript
  numberOf: number;
  level: number;
  positionFn: any;
  image?: HTMLImageElement;
}
```

**Comment by bafolts** [comment]
I pushed a fixed for this. Your input should run without error in 2.0.6

**Comment by David-Else** [comment]
Thanks!
