### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by JimTheMan** [bafolts/tplant#2]
Hi, I just cloned this repo and tried to run this command:

`./tplant.js ../sample/Class.ts`

but I'm getting this error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jameslynch/Git-Projects/tplant/bin/tplant.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by bafolts** [comment]
Did you run an `npm install` first? I see `commander` is in the `package.json` file.

https://github.com/bafolts/tplant/blob/master/package.json#L12
